Add separate script for ssh'ing to the provisioning directory.

diff --git a/{{ cookiecutter.project_slug }}/Vagrantfile b/{{ cookiecutter.project_slug }}/Vagrantfile
--- a/{{ cookiecutter.project_slug }}/Vagrantfile
+++ b/{{ cookiecutter.project_slug }}/Vagrantfile
@@ -1,24 +1,6 @@
 # -*- mode: ruby -*-
 # vi: set ft=ruby :
 
-$dev_vm_post_up_script = <<-SCRIPT
-sudo mount /opt/{{ cookiecutter.project_slug }}_backend/current/venv &> /dev/null || true
-sudo systemctl restart {{ cookiecutter.project_slug }} &> /dev/null || true
-SCRIPT
-
-$controller_vm_setup_script = <<-SCRIPT
-if ! grep -q "cd /vagrant/provisioning" ~/.bashrc ; then 
-  echo "cd /vagrant/provisioning" >> ~/.bashrc 
-fi
-# install ansible requirements
-sudo yum install -y epel-release
-sudo yum install -y python36 python36-pip python36-devel sshpass
-# Vagrant doesn't allow us to specify which version of pip/python is used to
-# install our provisioning requirements when using the 'ansible_local'
-# provisioner, so we set the system default to Python 3.
-sudo alternatives --install /usr/bin/pip pip /usr/bin/pip3.6 1
-SCRIPT
-
 Vagrant.require_version ">= 2.2.5"
 
 if Vagrant::Util::Platform.windows? then
@@ -82,13 +64,18 @@ Vagrant.configure("2") do |config|
       mount_options: ["uid=1234", "gid=1234"]
     )
 
-    # Ensure that the 'venv' folder is mounted after vagrant has configured
-    # its synced folders. Restart the backend app service - systemd may set
-    # this unit as failed shortly after boot since the files within the
-    # vagrant mount won't be available initially. These commands would fail on
-    # an initial 'vagrant up' without '|| true' since this script is executed
-    # *before* the first ansible provisioning is run (which adds this mount
-    # configuration into /etc/fstab and creates the systemd service).
+    $dev_vm_post_up_script = <<-SCRIPT
+      # Ensure that the 'venv' folder is mounted after vagrant has configured
+      # its synced folders. Restart the backend app service - systemd may set
+      # this unit as failed shortly after boot since the files within the
+      # vagrant mount won't be available initially. These commands would fail on
+      # an initial 'vagrant up' without '|| true' since this script is executed
+      # *before* the first ansible provisioning is run (which adds this mount
+      # configuration into /etc/fstab and creates the systemd service).
+      sudo mount /opt/{{ cookiecutter.project_slug }}_backend/current/venv &> /dev/null || true
+      sudo systemctl restart {{ cookiecutter.project_slug }} &> /dev/null || true
+    SCRIPT
+
     machine.vm.provision "shell", inline: $dev_vm_post_up_script, run: "always"
 
     machine.vm.network "private_network", ip: "172.17.177.21"
@@ -137,6 +124,16 @@ Vagrant.configure("2") do |config|
       virtualbox.name = "{{ cookiecutter.project_slug }}_controller"
       virtualbox.memory = 512
     end
+
+    $controller_vm_setup_script = <<-SCRIPT
+      # install ansible requirements
+      sudo yum install -y epel-release
+      sudo yum install -y python36 python36-pip python36-devel sshpass
+      # Vagrant doesn't allow us to specify which version of pip/python is used to
+      # install our provisioning requirements when using the 'ansible_local'
+      # provisioner, so we set the system default to Python 3.
+      sudo alternatives --install /usr/bin/pip pip /usr/bin/pip3.6 1
+    SCRIPT
 
     machine.vm.provision "shell", inline: $controller_vm_setup_script, privileged: false
 
